config/routes.rb
Rails.application.routes.draw do
  resources :images

  get '/generations/:id/question_cards', to: 'generations#question_cards'
  get '/generations/:id/answers', to: 'generations#answers'
  get 'generations/my', to: 'generations#my_generations'
  resources :generations

  get 'question_cards/my', to: 'question_cards#my_cards'
  get 'question_cards/:id/add_to_me', to: 'question_cards#add_to_me'
  resources :question_cards

  match 'tasks_groups/:id/add_task', to: 'tasks_groups#add_task', via: [:put]
  match 'tasks_groups/:id/remove_task', to: 'tasks_groups#remove_task', via: [:delete]
  get 'tasks_groups/my_groups'
  get 'tasks_groups/my', to: 'tasks_groups#my_groups'
  get 'tasks_groups/:id/add_to_me', to: 'tasks_groups#add_to_me'
  get 'tasks_groups/available_groups_for_add'
  resources :tasks_groups

  get 'tasks/my_tasks'
  get 'tasks/my', to: 'tasks#my_tasks'
  get 'tasks/:id/add_to_me', to: 'tasks#add_to_me'
  resources :tasks

  devise_for :users

  root 'main_page#index'

  get 'main_page/index'
  get 'main_page/welcome'
  get 'main_page/help'
  get 'help', to: 'main_page#help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  include PgSearch

  has_many :variables
  has_many :calculated_variables
  accepts_nested_attributes_for :variables, reject_if: lambda { |attributes| attributes['name'].blank? }
  accepts_nested_attributes_for :calculated_variables, reject_if: lambda { |attributes| attributes['name'].blank? }
  belongs_to :user
  has_and_belongs_to_many :tasks_groups, join_table: 'tasks_and_groups'
  has_many :generated_tasks

  validates_associated :variables
  validates_associated :calculated_variables
  validates :task, :title, presence: true

  pg_search_scope :search, against: [:title, :description, :subject, :task, :answer]

  def remove
    self.destroy unless if_linked { self.update(removed: true) }
  end

  def do_before_update
    if (task = if_linked { self.create_copy }).nil?
      self
    else
      self.update(removed: true)
      task
    end
  end

  def create_copy
    task = Task.new(self.attributes.merge({:id => nil}))
    task.transaction do
      task.save!
      self.variables.each { |v| task.variables.create!(v.attributes.merge({:id => nil})) }
      self.calculated_variables.each { |v| task.calculated_variables.create!(v.attributes.merge({:id => nil})) }
    end
    return task
  end

  private
  def if_linked
    unless self.generated_tasks.empty? && self.tasks_groups.empty?
      yield
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy, :my_tasks, :create, :update, :add_to_me]
  before_action :set_task, only: [:show, :edit, :destroy, :update, :add_to_me]
  before_action :auth, only: [:edit, :destroy, :update]

  # GET /tasks
  # GET /tasks.json
  def index
    query = params[:query]
    if query.nil? or query.blank?
      @tasks = Task.where(removed: false).paginate(:page => params[:page], :per_page => 10)
    else
      @tasks = Task.search(query).where(removed: false).paginate(:page => params[:page], :per_page => 10)
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/my_tasks
  # GET /tasks/my
  def my_tasks
    @tasks = current_user.tasks.where(removed: false)
    respond_to do |format|
      format.html
      format.json do
        render json: {type: @tasks.class.to_s, value: @tasks}
      end
    end
  end

  # GET /tasks/new
  def new
    @task = Task.new
    2.times { @task.variables.build }
    1.times { @task.calculated_variables.build }
  end

  # GET /tasks/1/edit
  def edit
    1.times { @task.variables.build } if @task.variables.size == 0
    1.times { @task.calculated_variables.build } if @task.calculated_variables.size == 0
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user = current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Задача успешно создана!' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /tasks/1/add_to_me
  def add_to_me
    @task = @task.create_copy
    @task.user = current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Задача успешно добавлена!' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @task = @task.do_before_update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.remove
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Задача была успешно удалена' }
      format.json { head :no_content }
    end
  end

  def auth
    unless current_user == @task.user
      redirect_to '/', alert: 'У Вас нет прав.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
      @variables = Variable.where(task: @task.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(
          :title, :description, :task, :answer, :subject,
          variables_attributes: [:id, :name, :from, :to, :round],
          calculated_variables_attributes: [:id, :name, :formula]
      )
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_add_task_to_group.html.erb
<% unless current_user.nil? %>
    <!-- .modal-dialog -->
    <div class="modal fade" id="addTaskModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 class="modal-title" id="myModalLabel">Добавление задачи в одну из групп</h4>
          </div>
          <div class="modal-body">
            <%= form_tag({}, id: 'add_task_form') do %>
                <%= hidden_field_tag :task_id %>
                <%= label_tag('Выберети группу, в которую вы хотите добавить задачу') %>
                <%= select_tag :group, {}, class: 'form-control' %>
            <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
            <button type="button" class="btn btn-primary" data-dismiss="modal" onclick="add_task()">Добавить</button>
          </div>
        </div>
        <!-- /.modal-content -->
      </div>
      <!-- /.modal-dialog -->
    </div>
<% end %>

app/views/tasks/_form.html.erb
<% if task.errors.any? %>
    <%=	render 'layouts/error', error: "Перед сохранением было обнаружены #{task.errors.count} ошибки!" %>
    <% task.errors.full_messages.each do |message| %>
        <%=	render 'layouts/error', error: message %>
    <% end %>
<% end %>

<%= form_for(task) do |f| %>
    <div class="field">
      <%= f.label 'Название задачи' %>
      <%= f.text_field :title, class: 'form-control', placeholder: 'Название', required: 1%>
    </div>

    <div class="field">
      <%= f.label 'Предмет' %>
      <%= f.text_field :subject, class: 'form-control', placeholder: 'Предмет' %>
    </div>

    <div class="field">
      <%= f.label 'Описание' %>
      <%= f.text_area :description, class: 'form-control', placeholder: 'Описание', maxlength: Rails.configuration.description_limit %>
    </div>

    <div class="field">
      <%= f.label 'Условие задачи' %>
      <%= f.text_area :task, id: "task", rows: 10, cols: 80, required: 1%>
      <script>
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace( 'task' );
      </script>
    </div>
    <br>

    <div class="panel panel-default">
      <div class="panel-heading">
        <table width="100%"><tr>
          <td>Генерируемые переменные</td>
          <td align="right" width="100px">
            <button type="button" class="btn btn-success btn-xs" onclick="addVariableForm('variable-forms')">
              <i class="fa fa-plus"></i> Добавить переменную
            </button>
          </td>
        </tr></table>
      </div>
      <ul class="list-group" id="variable-forms">
        <%= f.fields_for :variables do |v| %>
            <li class="list-group-item">
              <button type="button" class="close" onclick="removeVariableForm(this.parentElement, 'variable-forms')">×</button>
              <div class="row" style="margin-right: 13px">
                <div class="col-md-4">
                  <div class="form">
                    <div class="input-group">
                      <span class="input-group-addon">$</span>
                      <%= v.text_field :name, class: 'form-control', placeholder: 'Имя переменной'%>
                    </div>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="form">
                    <div class="input-group">
                      <span class="input-group-addon">от</span>
                      <%= v.number_field :from, class: 'form-control', placeholder: 'Нижняя граница', step: 'any' %>
                    </div>
                  </div>
                </div>
                <div class="col-md-3">
                  <div class="form">
                    <div class="input-group">
                      <span class="input-group-addon">до</span>
                      <%= v.number_field :to, class: 'form-control', placeholder: 'Верхняя граница', step: 'any' %>
                    </div>
                  </div>
                </div>
                <div class="col-md-2">
                  <div class="form">
                    <div class="input-group">
                      <span class="input-group-addon">0.0</span>
                      <%= v.number_field :round, class: 'form-control', placeholder: 'Округление'%>
                    </div>
                  </div>
                </div>
              </div>
            </li>
        <% end %>
      </ul>
    </div>

    <div class="field">
      <%= f.label 'Решение' %>
      <%= f.text_area :answer, id: 'answer', class: 'form-control', rows: 5 %>
      <script>
        // Replace the <textarea id="editor1"> with a CKEditor
        // instance, using default configuration.
        CKEDITOR.replace( 'answer' );
      </script>
    </div>
    <br>

    <div class="panel panel-default">
      <div class="panel-heading">
        <table width="100%"><tr>
          <td>Вычисляемые переменные</td>
          <td align="right" width="100px">
            <button type="button" class="btn btn-success btn-xs" onclick="addVariableForm('calculated_variable-forms')">
              <i class="fa fa-plus"></i> Добавить переменную
            </button>
          </td>
        </tr></table>
      </div>
      <ul class="list-group" id="calculated_variable-forms">
        <%= f.fields_for :calculated_variables do |v| %>
            <li class="list-group-item">
              <button type="button" class="close"
                      onclick="removeVariableForm(this.parentElement, 'calculated_variable-forms')">×</button>
              <div class="row" style="margin-right: 13px">
                <div class="col-md-4">
                  <div class="form">
                    <div class="input-group">
                      <span class="input-group-addon">$</span>
                      <%= v.text_field :name, class: 'form-control', placeholder: 'Имя переменной'%>
                    </div>
                  </div>
                </div>
                <div class="col-md-8">
                  <div class="form">
                    <div class="input-group">
                      <span class="input-group-addon"><i>f<sub>x</sub></i></span>
                      <%= v.text_field :formula, class: 'form-control', placeholder: 'Формула: $a + $b / 2'%>
                    </div>
                  </div>
                </div>
              </div>
            </li>
        <% end %>
      </ul>
    </div>

    <br>
    <div class="actions">
      <%= f.submit task.persisted? ? 'Изменить' : 'Создать', class: 'btn btn-default'%>
      <%= link_to 'Назад', :back, class: 'btn btn-link' %>
    </div>

<% end %>

app/views/tasks/_list_item.html.erb
<a href="<%= task_path task %>" class="list-group-item list-group-item-action">
  <table class="list-group-item-title"><tr><td>
    <% unless current_user.nil? %>
        <div style="float: right">
          <% if current_user == task.user %>
              <a href="<%= edit_task_path(task) %>" type="button" class="btn btn-warning btn-circle btn-xs"
                 data-placement="bottom" data-toggle="tooltip" title="Редактировать">
                <i class="fa fa-edit"></i>
              </a>

              <a href="javascript: document.getElementById('form-destroy_task_<%= task.id %>').submit()" aria-hidden="true"
                 data-toggle="confirmation" data-placement="bottom" title="Вы уверены, что хотите удалить эту задачу?">
                <button type="button" class="btn btn-danger btn-circle btn-xs" data-toggle="tooltip"
                        data-placement="bottom" title="Удалить" data-trigger="hover">
                  <i class="fa fa-trash-o"></i>
                </button>
              </a>
          <% end %>
          <a href="javascript: openModalAddTask(<%= task.id %>)" type="button" title="Добавить в группу с задачами"
                  class="btn btn-success btn-circle btn-outline btn-xs" data-placement="bottom" data-toggle="tooltip">
            <i class="fa fa-plus-square"></i>
          </a>
          <% unless current_user == task.user %>
              <a href="<%= task_path task %>/add_to_me" class="btn btn-success btn-circle btn-xs"
                 data-placement="bottom" data-toggle="tooltip" title="Добавить к себе">
                <i class="fa fa-plus"></i>
              </a>
          <% end %>
        </div>
        <%= form_tag task_path(task), method: 'delete', id: 'form-destroy_task_' + task.id.to_s do end %>
    <% end %>
    <h4 class="list-group-item-heading "><%= task.title %></h4>
  </td></tr></table>

  <p class="list-group-item-text list-group-item-description"><%= task.description %></p>

  <table width="100%"><tr>
      <td><p class="list-group-item-buttom">
        <small><i><b>Предмет:</b> <%= task.subject %></i></small><br>
        <small><i><a target="_blank" href="http://<%= task.user.email %>"><%= task.user.email %></a></i></small>
      </p></td>
      <td width="80px" valign="bottom">
        <span class="pull-right text-muted small"><em><%= task.updated_at.to_formatted_s(:short) %></em></span>
      </td>
  </tr></table>
</a>

app/views/tasks/edit.html.erb
<h1 class="page-header">Редактирование задачи</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1 class="page-header">Задачи</h1>

<%= form_tag("/tasks", method: "get") do %>
    <div class="input-group">
      <%= text_field_tag :query, params[:query], class: "form-control ui-autocomplete-input", placeholder: "Поиск на сайте" %>
      <span class="input-group-btn">
			  <button type="submit" class="btn btn-default"><i class="fa fa-search"></i> Найти</button>
      </span>
    </div><br>

    <ul class="nav nav-pills">
      <li><%= submit_tag 'Задачи', class: 'btn btn-primary', formaction: tasks_path %></li>
      <li class="pill-buttons">
        <%= submit_tag 'Билеты', class: 'btn btn-primary btn-outline', formaction: question_cards_path %>
      </li>
      <li><%= submit_tag 'Группы задач', class: 'btn btn-primary btn-outline', formaction: tasks_groups_path %></li>
    </ul>
<% end %>
<br><br>

<%= render 'add_task_to_group' %>
<div class="list-group">
  <% @tasks.each do |task| %>
    <%= render 'list_item', task: task %>
  <% end %>
</div>

<br>

<%= will_paginate @tasks, renderer: BootstrapPagination::Rails %>

app/views/tasks/my_tasks.html.erb
<h1 class="page-header">
  <table width="100%"><tr>
    <td>Ваши задачи:</td>
    <td width="220px" align="right">
      <a href="<%= new_task_path %>" type="button" class="btn btn-success"><i class="fa fa-plus"></i> Добавить новую</a>
    </td>
  </tr></table>
</h1>

<% if @tasks.size == 0 %>
    <p>Вы еще не добавили ни одной задачи. Сделать это вы можете <%= link_to 'здесь', new_task_path %></p>
<% else %>
    <%= render 'add_task_to_group' %>
    <div class="list-group">
      <% @tasks.each do |task| %>
          <%= render 'list_item', task: task %>
      <% end %>
    </div>
<% end %>

app/views/tasks/new.html.erb
<h1 class="page-header" >Новая задача</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<%= render 'add_task_to_group' %>

<%= form_tag task_path(@task), method: 'delete', id: 'form-destroy' do end %>

<h1 class="page-header" >
  <table width="100%"><tr>
    <td>
      <b>Задача:</b> <%= @task.title %>
    </td>
    <% unless current_user.nil? %>
        <td width="220px" align="right">
          <% if current_user == @task.user %>
              <a href="<%= edit_task_path(@task) %>" class="btn btn-warning btn-circle"
                 data-placement="bottom" data-toggle="tooltip" title="Редактировать">
                <i class="fa fa-edit"></i>
              </a>

              <a href="javascript: document.getElementById('form-destroy').submit()" class="btn btn-danger btn-circle"
                 aria-hidden="true" data-toggle="confirmation" data-placement="bottom"
                 title="Вы уверены, что хотите удалить эту задачу?">
                <i class="fa fa-trash-o"></i>
              </a>
          <% end %>

          <button onclick="openModalAddTask(<%= @task.id %>)" type="button"
                  class="btn btn-success btn-circle btn-outline" data-placement="bottom" data-toggle="tooltip"
                  title="Добавить в группу с задачами">
            <i class="fa fa-plus-square"></i>
          </button>

          <% unless current_user == @task.user %>
              <a href="<%= task_path @task %>/add_to_me" class="btn btn-success btn-circle" data-placement="bottom"
                 data-toggle="tooltip" title="Добавить к себе">
                <i class="fa fa-plus"></i>
              </a>
          <% end %>
          <!--<button class="btn btn-primary" data-toggle="modal" data-target="#generateModal">-->
          <!--Сгенерировать-->
          <!--</button>-->
        </td>
    <% end %>
  </tr></table>
</h1>

<table width="100%">
  <tr>
    <td>
      <p>
        <strong>Пользователь:</strong>
        <i><a target="_blank" href="http://<%= @task.user.email %>"><%= @task.user.email %></a> </i>
      </p>
    </td>
    <td>
      <p style="text-align: right;">
        <%= @task.updated_at.to_formatted_s(:long) %>
      </p>
    </td>
  </tr>
</table>

<h5><strong>Предмет: </strong><%= @task.subject %></h5>

<div class="panel panel-default">
  <div class="panel-heading">
    Описание:
  </div>
  <div class="panel-body">
    <%= @task.description %>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    Условие задачи:
  </div>
  <div class="panel-body">
    <%= raw @task.task %>
  </div>
</div>

<div class="panel panel-warning">
  <div class="panel-heading">
    Решение:
  </div>
  <div class="panel-body">
    <%= raw @task.answer %>
  </div>
</div>