config/routes.rb
Rails.application.routes.draw do
  resources :images

  get '/generations/:id/question_cards', to: 'generations#question_cards'
  get '/generations/:id/answers', to: 'generations#answers'
  get 'generations/my', to: 'generations#my_generations'
  resources :generations

  get 'question_cards/my', to: 'question_cards#my_cards'
  get 'question_cards/:id/add_to_me', to: 'question_cards#add_to_me'
  resources :question_cards

  match 'tasks_groups/:id/add_task', to: 'tasks_groups#add_task', via: [:put]
  match 'tasks_groups/:id/remove_task', to: 'tasks_groups#remove_task', via: [:delete]
  get 'tasks_groups/my_groups'
  get 'tasks_groups/my', to: 'tasks_groups#my_groups'
  get 'tasks_groups/:id/add_to_me', to: 'tasks_groups#add_to_me'
  get 'tasks_groups/available_groups_for_add'
  resources :tasks_groups

  get 'tasks/my_tasks'
  get 'tasks/my', to: 'tasks#my_tasks'
  get 'tasks/:id/add_to_me', to: 'tasks#add_to_me'
  resources :tasks

  devise_for :users

  root 'main_page#index'

  get 'main_page/index'
  get 'main_page/welcome'
  get 'main_page/help'
  get 'help', to: 'main_page#help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tasks_group.rb
class TasksGroup < ApplicationRecord
  include PgSearch

  belongs_to :user
  has_and_belongs_to_many :tasks, join_table: 'tasks_and_groups'

  validates :title, presence: true

  pg_search_scope :search, against: [:title, :description, :subject]

  before_destroy do
    self.tasks.each { |t| t.destroy if t.removed && t.generated_tasks.empty? }
  end

  def remove
    self.destroy unless if_linked { self.update(removed: true) }
  end

  def do_before_update
    if (group = if_linked { self.create_copy }).nil?
      self
    else
      self.update(removed: true)
      group
    end
  end

  def create_copy
    g = TasksGroup.new(self.attributes.merge({:id => nil}))
    g.transaction do
      g.save!
      self.tasks.each { |t| g.tasks.create!(t.attributes.merge({:id => nil})) }
    end
    return g
  end

  private
  def if_linked
    if QuestionCard.all.any? do |card|
      Nokogiri::HTML(card.question_card).css('.task').any? { |t| t[:tasks_group_id].to_i == self.id }
    end
      yield
    end
  end
end

app/controllers/tasks_groups_controller.rb
class TasksGroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy, :my_groups, :create, :update, :remove_task,
                                            :add_task, :add_to_me]
  before_action :set_tasks_group, only: [:show, :edit, :update, :destroy, :add_task, :remove_task, :add_to_me]
  before_action :auth, only: [:edit, :update, :destroy, :add_task, :remove_task]

  # GET /tasks_groups
  # GET /tasks_groups.json
  def index
    query = params[:query]
    @tasks_groups =
        if query.nil? or query.blank?
          TasksGroup.where(removed: false).paginate(:page => params[:page], :per_page => 10)
        else
          TasksGroup.search(query).where(removed: false).paginate(:page => params[:page], :per_page => 10)
        end
  end

  # GET /tasks_groups/my_groups
  # GET /tasks_groups/my_groups.json
  def my_groups
    @tasks_groups = current_user.tasks_groups.where(removed: false)
    respond_to do |format|
      format.html
      format.json do
        render json: {type: @tasks_groups.class.to_s, value: @tasks_groups}
      end
    end
  end

  # GET /tasks_groups/available_groups_for_add.json
  def available_groups_for_add
    @tasks_groups = current_user.tasks_groups.select { |g| !g.tasks.exists?(params[:task_id]) }
    respond_to do |format|
      format.json { render 'index' }
    end
  end

  # GET /tasks_groups/1
  # GET /tasks_groups/1.json
  def show
  end

  # GET /tasks_groups/new
  def new
    @tasks_group = TasksGroup.new
  end

  # GET /tasks_groups/1/edit
  def edit
  end

  # POST /tasks_groups
  # POST /tasks_groups.json
  def create
    @tasks_group = TasksGroup.new(tasks_group_params)
    @tasks_group.user = current_user

    respond_to do |format|
      if @tasks_group.save
        format.html { redirect_to @tasks_group, notice: 'Tasks group was successfully created.' }
        format.json { render :show, status: :created, location: @tasks_group }
      else
        format.html { render :new }
        format.json { render json: @tasks_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /tasks_groups/1/add_to_me
  def add_to_me
    @tasks_group = @tasks_group.create_copy
    @tasks_group.user = current_user

    respond_to do |format|
      if @tasks_group.save
        format.html { redirect_to @tasks_group, notice: 'Задача успешно добавлена!' }
        format.json { render :show, status: :created, location: @tasks_group }
      else
        format.html { render :new }
        format.json { render json: @tasks_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks_groups/1
  # PATCH/PUT /tasks_groups/1.json
  def update
    @tasks_group = @tasks_group.do_before_update
    respond_to do |format|
      if @tasks_group.update(tasks_group_params)
        format.html { redirect_to @tasks_group, notice: 'Tasks group was successfully updated.' }
        format.json { render :show, status: :ok, location: @tasks_group }
      else
        format.html { render :edit }
        format.json { render json: @tasks_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks_groups/1/add_task.json
  def add_task
    @tasks_group.tasks << Task.find( params.require(:task_id) )
    respond_to do |format|
      if !@tasks_group.errors.any?
        format.json { render json: {notice: "Задача успешно добавлена в группу: #{@tasks_group.title}"}, status: :ok }
      else
        format.json { render json: @tasks_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks_groups/1/remove_task.json
  def remove_task
    @tasks_group.tasks.delete( params.require(:task_id) )
    respond_to do |format|
      format.json { render json: {notice: "Задача успешно удалена из группы: #{@tasks_group.title}"}, status: :ok }
    end
  end

  # DELETE /tasks_groups/1
  # DELETE /tasks_groups/1.json
  def destroy
    @tasks_group.remove
    respond_to do |format|
      format.html { redirect_to tasks_groups_url, notice: 'Tasks group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def auth
    unless current_user == @tasks_group.user
      redirect_to '/', alert: 'У Вас нет прав.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tasks_group
      @tasks_group = TasksGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tasks_group_params
      params.require(:tasks_group).permit(:user, :subject, :title, :description, :date)
    end
end

app/helpers/tasks_groups_helper.rb
module TasksGroupsHelper
end

app/views/tasks_groups/_form.html.erb
<% if tasks_group.errors.any? %>
    <%=	render 'layouts/error', error: "Перед сохранением было обнаружены #{tasks_group.errors.count} ошибки!" %>
    <% tasks_group.errors.full_messages.each do |message| %>
        <%=	render 'layouts/error', error: message %>
    <% end %>
<% end %>

<%= form_for(tasks_group) do |f| %>
    <div class="field">
      <%= f.label 'Название группы задач' %>
      <%= f.text_field :title, class: 'form-control', placeholder: 'Название', required: 1 %>
    </div>

    <div class="field">
      <%= f.label 'Предмет' %>
      <%= f.text_field :subject, class: 'form-control', placeholder: 'Предмет' %>
    </div>

    <div class="field">
      <%= f.label 'Описание' %>
      <%= f.text_area :description, class: 'form-control', placeholder: 'Описание', maxlength: Rails.configuration.description_limit %>
    </div>
<br>
  <div class="actions">
    <%= f.submit tasks_group.persisted? ? 'Изменить' : 'Создать', class: 'btn btn-default'%>
    <%= link_to 'Назад', :back, class: 'btn btn-link' %>
  </div>
<% end %>

app/views/tasks_groups/_list_item.html.erb
<a href="<%= tasks_group_path group %>" class="list-group-item list-group-item-action">
  <table class="list-group-item-title"><tr><td>
    <div style="float: right">
      <% unless current_user.nil? %>
          <% if current_user == group.user %>
              <a href="<%= edit_tasks_group_path(group) %>" type="button"
                 class="btn btn-warning btn-circle btn-xs" data-placement="bottom" data-toggle="tooltip"
                 title="Редактировать">
                <i class="fa fa-edit"></i>
              </a>
              <a href="javascript: document.getElementById('form-destroy-tasks_group_<%= group.id %>').submit()"
                 aria-hidden="true" data-toggle="confirmation" data-placement="bottom"
                 title="Вы уверены, что хотите удалить эту группу задач?">
                <button type="button" class="btn btn-danger btn-circle btn-xs" data-toggle="tooltip"
                        data-placement="bottom" title="Удалить" data-trigger="hover">
                  <i class="fa fa-trash-o"></i>
                </button>
              </a>
          <% else %>
              <a href="<%= tasks_group_path group %>/add_to_me" class="btn btn-success btn-circle btn-xs"
                 data-placement="bottom" data-toggle="tooltip" title="Добавить к себе">
                <i class="fa fa-plus"></i>
              </a>
          <% end %>
      <% end %>
    </div>
    <h4 class="list-group-item-heading"><%= group.title %></h4>
    <%= form_tag tasks_group_path(group), method: 'delete', id: 'form-destroy-tasks_group_' + group.id.to_s do end %>
  </td></tr></table>

  <p class="list-group-item-text list-group-item-description"><%= group.description %></p>

  <table width="100%">
    <tr>
      <td><p class="list-group-item-buttom">
        <small><i><b>Предмет:</b> <%= group.subject %></i></small><br>
        <small><i><b>Количество задач:</b> <%= group.tasks.size %></i></small><br>
        <small><i><a target="_blank" href="http://<%= group.user.email %>"><%= group.user.email %></a></i></small>
      </p></td>
      <td width="80px" valign="bottom">
        <span class="pull-right text-muted small"><em><%= group.updated_at.to_formatted_s(:short) %></em></span>
      </td>
    </tr>
  </table>
</a>

app/views/tasks_groups/edit.html.erb
<h1>Редактирование группы задач</h1>

<%= render 'form', tasks_group: @tasks_group %>

app/views/tasks_groups/index.html.erb
<h1 class="page-header">Группы задач</h1>

<%= form_tag("/tasks_groups", method: "get") do %>
    <div class="input-group">
      <%= text_field_tag :query, params[:query], class: "form-control ui-autocomplete-input",
                         placeholder: "Поиск на сайте" %>
      <span class="input-group-btn">
			  <button type="submit" class="btn btn-default"><i class="fa fa-search"></i> Найти</button>
      </span>
    </div><br>

    <ul class="nav nav-pills">
      <li><button class="btn btn-primary btn-outline" type="submit" formaction="/tasks">Задачи</button></li>
      <li class="pill-buttons"><button class="btn btn-primary btn-outline" type="submit" formaction="/question_cards">
        Билеты
      </button></li>
      <li><button class="btn btn-primary" type="submit" formaction="/tasks_groups">Группы задач</button>
      </li>
    </ul>
<% end %>
<br><br>

<div class="list-group">
  <% @tasks_groups.each do |group| %>
      <%= render 'list_item', group: group %>
  <% end %>
</div>

<br>

<%= will_paginate @tasks_groups, renderer: BootstrapPagination::Rails %>

app/views/tasks_groups/my_groups.html.erb
<h1 class="page-header">
  <table width="100%"><tr>
    <td>Ваши группы задач:</td>
    <td width="220px" align="right">
      <a href="<%= new_task_path %>" type="button" class="btn btn-success"><i class="fa fa-plus"></i> Добавить новую</a>
    </td>
  </tr></table>
</h1>

<% if @tasks_groups.size == 0 %>
    <p>Вы пока еще не создали ни одной группы задачи. Сделать это вы можете
      <%= link_to 'здесь', new_tasks_group_path %>
    </p>
<% else %>
    <div class="list-group">
      <% @tasks_groups.each do |group| %>
          <%= render 'tasks_groups/list_item', group: group %>
      <% end %>
    </div>
<% end %>

app/views/tasks_groups/new.html.erb
<h1 class="page-header">Новая группа задач</h1>

<%= render 'form', tasks_group: @tasks_group %>

app/views/tasks_groups/show.html.erb
<%= form_tag tasks_group_path(@tasks_group), method: 'delete', id: 'form-destroy' do end %>

<h1 class="page-header" >
  <table width="100%"><tr>
    <td>
      <b>Группа задач:</b> <%= @tasks_group.title %>
    </td>
    <% unless current_user.nil? %>
        <td width="200px" align="right">
          <% if current_user == @tasks_group.user %>
              <button type="button" class="btn btn-warning btn-circle" data-placement="bottom" data-toggle="tooltip"
                      title="Изменить">
                <i class="fa fa-edit"></i>
              </button>

              <a href="javascript: document.getElementById('form-destroy').submit()" class="btn btn-danger btn-circle"
                 aria-hidden="true" data-toggle="confirmation" data-placement="bottom"
                 title="Вы уверены, что хотите удалить эту группу задач?">
                <i class="fa fa-trash-o"></i>
              </a>
          <% end %>

          <!--<button type="button" class="btn btn-info btn-circle btn-outline" data-placement="bottom" data-toggle="tooltip" title="Добавить в группу с задачами">-->
          <!--<i class="fa fa-tasks"></i>-->
          <!--</button>-->
          <% unless current_user == @tasks_group.user %>
              <a href="<%= tasks_group_path @tasks_group %>/add_to_me" class="btn btn-success btn-circle"
                 data-placement="bottom" data-toggle="tooltip" title="Добавить к себе">
                <i class="fa fa-plus"></i>
              </a>
          <% end %>
        </td>
    <% end %>
  </tr></table>
</h1>

<table width="100%">
  <tr>
    <td>
      <p>
        <strong>Пользователь:</strong>
        <i><a target="_blank" href="http://<%= @tasks_group.user.email %>"><%= @tasks_group.user.email %></a> </i>
      </p>
    </td>
    <td>
      <p style="text-align: right;">
        <%= @tasks_group.created_at %>
      </p>
    </td>
  </tr>
</table>

<h5>
  <strong>Предмет: </strong>
  <%= @tasks_group.subject %>
</h5>

<div class="panel panel-default">
  <div class="panel-heading">
    Описание
  </div>
  <div class="panel-body">
    <%= @tasks_group.description %>
  </div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    Задачи входящие в эту группу
  </div>
  <!-- .panel-heading -->
  <div class="panel-body">
    <div class="panel-group" id="tasks_in_group">
      <%= 'В данную группу еще не добавлены задачи' if @tasks_group.tasks.size == 0 %>
      <% @tasks_group.tasks.each_with_index do |task, i| %>
          <div class="panel panel-default" id="task_<%= task.id %>">
            <div class="panel-heading">
              <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#tasks_in_group" href="#collapse<%= i %>">
                  <%= task.title %>
                </a>
                <button type="button" class="close" aria-hidden="true" data-toggle="confirmation"
                        data-on-confirm="remove_task" group="<%= @tasks_group.id %>" task_id="<%= task.id %>"
                        data-placement="left" title="Вы уверены, что хотите убрать задачу из группы?">×</button>
              </h4>
            </div>
            <div id="collapse<%= i %>" class="panel-collapse collapse <%= 'in' if i == 0 %>">
              <div class="panel-body">
                <%= task.description %>
                <div style="padding-top: 10px;">
                  <a href="/tasks/<%= task.id %>" ><button type="button" class="btn btn-default btn-sm">Перейти к задаче</button></a>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
  <!-- .panel-body -->
</div>

<%= link_to 'Edit', edit_tasks_group_path(@tasks_group) %> |
<%= link_to 'Back', tasks_groups_path %>

<!-- Скрипт для инициализации элементов на странице, имеющих атрибут data-toggle="confirmation-remove-task-from-group" -->
<script>
  // после загрузки страницы
  $(function () {
    // инициализировать все элементы на страницы, имеющих атрибут data-toggle="tooltip", как компоненты tooltip
    $('[data-toggle="confirmation-remove-task-from-group"]').confirmation({
      singleton:true,
      btnOkLabel: 'Да', btnCancelLabel: 'Нет',
      btnOkClass: 'btn-sm btn-primary', btnCancelClass: 'btn-sm btn-default',
      buttons: [
        {
          label: 'Approved',
          class: 'btn btn-xs btn-success',
          icon: 'glyphicon glyphicon-ok'
        },
        {
          label: 'Rejected',
          class: 'btn btn-xs btn-danger',
          icon: 'glyphicon glyphicon-remove'
        },
        {
          label: 'Need review',
          class: 'btn btn-xs btn-warning',
          icon: 'glyphicon glyphicon-search'
        },
        {
          label: 'Decide later',
          class: 'btn btn-xs btn-default',
          icon: 'glyphicon glyphicon-time'
        }
      ]
    });
  })
</script>