config/routes.rb
Rails.application.routes.draw do
  resources :images

  get '/generations/:id/question_cards', to: 'generations#question_cards'
  get '/generations/:id/answers', to: 'generations#answers'
  get 'generations/my', to: 'generations#my_generations'
  resources :generations

  get 'question_cards/my', to: 'question_cards#my_cards'
  get 'question_cards/:id/add_to_me', to: 'question_cards#add_to_me'
  resources :question_cards

  match 'tasks_groups/:id/add_task', to: 'tasks_groups#add_task', via: [:put]
  match 'tasks_groups/:id/remove_task', to: 'tasks_groups#remove_task', via: [:delete]
  get 'tasks_groups/my_groups'
  get 'tasks_groups/my', to: 'tasks_groups#my_groups'
  get 'tasks_groups/:id/add_to_me', to: 'tasks_groups#add_to_me'
  get 'tasks_groups/available_groups_for_add'
  resources :tasks_groups

  get 'tasks/my_tasks'
  get 'tasks/my', to: 'tasks#my_tasks'
  get 'tasks/:id/add_to_me', to: 'tasks#add_to_me'
  resources :tasks

  devise_for :users

  root 'main_page#index'

  get 'main_page/index'
  get 'main_page/welcome'
  get 'main_page/help'
  get 'help', to: 'main_page#help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/generation.rb
class Generation < ApplicationRecord
  belongs_to :user
  belongs_to :question_card
  has_many :variants, dependent: :destroy

  before_destroy do
    self.question_card.destroy if self.question_card.removed
  end
end

app/controllers/generations_controller.rb
class GenerationsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy, :my_generations]
  before_action :set_generation, only: [:show, :destroy, :question_cards, :answers]
  before_action :auth, only: [:destroy]

  # GET /generations
  # GET /generations.json
  def index
    @generations = Generation.all
  end

  def my_generations
    @generations = current_user.generations.sort { |a, b| b.updated_at <=> a.updated_at }
    respond_to do |format|
      format.html
      format.json do
        render json: @generations
      end
    end
  end

  # GET /generations/1
  # GET /generations/1.json
  def show
  end

  # GET /generations/1/question_cards
  # GET /generations/1/question_cards.pdf
  def question_cards
    template = @generation.question_card.question_card
    @cards = @generation.variants.map do |v|
      card = template.gsub('$V', v.number.to_s)

      doc = Nokogiri::HTML(card)
      doc.css('.task').each do |task|
        task.inner_html = generate_task_text( v.generated_tasks.find_by(task_in_card: task[:id].to_i) )
      end
      doc.to_html
    end

    respond_to do |format|
      format.html { render layout: false }
      format.pdf do
        orientation = params[:orientation] ? 'Portrait' : 'Landscape'
        render pdf: "question_card",   # Excluding ".pdf" extension.
          orientation: orientation
      end
    end
  end

  # GET /generations/1/answers
  # GET /generations/1/answers.pdf
  def answers
    card = @generation.question_card.question_card
    @answers = @generation.variants.map do |v|
      tasks = Nokogiri::HTML(card).css('.task').map do |task|
        gen_task = v.generated_tasks.find_by(task_in_card: task[:id].to_i)
        task_text = generate_task_text( gen_task )
        t = gen_task.task

        generated_variables = gen_task.generated_variables.map { |var| [var.variable.name, var.value] }.to_h

        t.calculated_variables.each do |var|
          res = calculate(var.formula, generated_variables)
          generated_variables[var.name] = res
        end
        answer = paste_variables(t.answer, generated_variables)

        {
            name: task[:task_name],
            task: t,
            task_text: task_text,
            answer: answer
        }
      end
      {
          variant: v.number,
          tasks_in_card: tasks
      }
    end

    respond_to do |format|
      format.html { render layout: false }
      format.pdf do
        orientation = params[:orientation] ? 'Portrait' : 'Landscape'
        render pdf: "answers",   # Excluding ".pdf" extension.
          orientation: orientation
      end
    end
  end

  # POST /generations
  # POST /generations.json
  def create
    @generation = Generation.new(generation_params)
    @generation.user = current_user

    @generation.transaction do
      @generation.save!
      tasks_in_card = Nokogiri::HTML(@generation.question_card.question_card).css('.task')
      params.require(:number_variants).to_i.times do |i|
        variant = Variant.create!(number: i + 1, generation: @generation)
        tasks_in_card.each do |task|
          task_id = task[:task_id].to_i
          if task_id == 0
            tasks = TasksGroup.find(task[:tasks_group_id].to_i).tasks.ids
            generated_tasks = @generation.question_card.generated_tasks.map { |t| t.task.id }
            tasks -= generated_tasks if tasks.count > generated_tasks.count
            task_id = tasks.shuffle.first
          end
          generated_task = GeneratedTask.create!(variant: variant, task_in_card: task[:id].to_i, task_id: task_id)

          generated_task.task.variables.each do |v|
            rnd = Random.new
            res = rnd.rand(v.from .. v.to)
            res = res.round(v.round) unless v.round.nil?
            GeneratedVariable.create!(generated_task: generated_task, variable: v, value: res)
          end
        end
      end
    end

    respond_to do |format|
      if !@generation.errors.any?
        format.html { redirect_to @generation, notice: 'Generation was successfully created.' }
        format.json { render :show, status: :created, location: @generation }
      else
        format.html { render :new }
        format.json { render json: @generation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generations/1
  # DELETE /generations/1.json
  def destroy
    @generation.destroy
    respond_to do |format|
      format.html { redirect_to generations_my_url, notice: 'Сгенерированные варианты были успешно удалены.' }
      format.json { head :no_content }
    end
  end

  def paste_variables(text, variables)
    variables.keys.sort { |a, b| b <=> a }.each { |name| text.gsub!('$' + name, variables[name].to_s) }
    text
  end

  def generate_task_text(generated_task)
    variables = generated_task.generated_variables.map { |v| [v.variable.name, v.value] }.to_h
    paste_variables(generated_task.task.task, variables)
  end

  def calculate(ex, generated_variables)
    ex = paste_variables(ex, generated_variables)
    Rails.cache.fetch("#{Rails.configuration.cache_answer_key}/#{ex}", expires_in: 12.hours) do
      options = { "format" => "plaintext" }
      client = WolframAlpha::Client.new Rails.configuration.wolfram_api, options
      response = client.query ex + '+0'
      result = response.find { |pod| pod.title == "Result" }
      result.subpods[0].plaintext
    end
  end

  def auth
    unless current_user == @generation.user
      redirect_to '/', alert: 'У Вас нет прав.'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_generation
    @generation = Generation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def generation_params
    params.permit(:question_card_id, :title)
  end
end

app/helpers/generations_helper.rb
module GenerationsHelper
end

app/views/generations/_form.html.erb
<%= form_for(generation) do |f| %>
  <% if generation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(generation.errors.count, "error") %> prohibited this generation from being saved:</h2>

      <ul>
      <% generation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :question_card_id %>
    <%= f.number_field :question_card_id %>
  </div>

  <div class="field">
    <%= f.label :page_layout_id %>
    <%= f.number_field :page_layout_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/generations/_generate_modal.html.erb
<!-- .modal-dialog -->
<div class="modal fade" id="generateModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title" id="myModalLabel">Сгенерировать билеты</h4>
      </div>
      <div class="modal-body">
        <%= form_tag("/generations", method: 'post', id: 'form-generator') do %>
            <%= hidden_field_tag :question_card_id %>
            <%= label_tag('Заголовок') %>
            <%= text_field_tag :title, '', class: 'form-control', placeholder: 'Сгенерированные задачи для дз'  %><br>
            <%= label_tag('Количество вариантов') %>
            <%= number_field_tag :number_variants, 1, class: 'form-control', min: 1,
                                 max: Rails.configuration.max_variants %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" form="form-generator">Сгенерировать</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

app/views/generations/_list_item.erb
<a href="<%= generation_path generation %>" class="list-group-item list-group-item-action">
  <button href="javascript: document.getElementById('form-destroy_generation_<%= generation.id %>').submit()" class="close"
     aria-hidden="true" data-toggle="confirmation" data-placement="left"
     title="Вы уверены, что хотите удалить эти сгенерированные варианты?">×</button>
  <%= form_tag generation_path(generation), method: 'delete', id: 'form-destroy_generation_' + generation.id.to_s do end %>

  <h5 style="margin: 0px;">
    <%= generation.title %>
  </h5>

  <table width="100%">
    <tr>
      <td><p class="list-group-item-buttom">
        <small><%= generation.variants.size %> вариантов</small>
      </p></td>
      <td width="80px" valign="bottom">
        <span class="pull-right text-muted small"><em><%= generation.updated_at.to_formatted_s(:short) %></em></span>
      </td>
    </tr>
  </table>
</a>

app/views/generations/answers.html.erb
<meta charset="UTF-8">
<% @answers.each do |v| %>
    <h1>Вариант № <%= v[:variant] %></h1>
    <% v[:tasks_in_card].each do |t| %>
        <h2>Задача № <%= t[:name] %></h2>
        <h3>Условие:</h3>
        <%= raw t[:task_text]  %>
        <h3>Решение:</h3>
        <%= raw t[:answer]  %>
    <% end %>

    <% case params[:page_layout].to_i %>
      <% when 0 %>
        <hr>
      <% when 1 %>
        <div style="page-break-after: always"></div>
    <% end %>
<% end %>

app/views/generations/answers.pdf.erb
<meta charset="UTF-8">
<% @answers.each do |v| %>
    <h1>Вариант № <%= v[:variant] %></h1>
    <% v[:tasks_in_card].each do |t| %>
        <h2>Задача № <%= t[:name] %></h2>
        <h3>Условие:</h3>
        <%= raw t[:task_text]  %>
        <h3>Решение:</h3>
        <%= raw t[:answer]  %>
    <% end %>
    <% case params[:page_layout].to_i %>
      <% when 0 %>
        <hr>
      <% when 1 %>
        <div style="page-break-after: always"></div>
    <% end %>
<% end %>

app/views/generations/edit.html.erb
<h1>Editing Generation</h1>

<%= render 'form', generation: @generation %>

<%= link_to 'Show', @generation %> |
<%= link_to 'Back', generations_path %>

app/views/generations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Generations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Question card</th>
      <th>Page layout</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @generations.each do |generation| %>
      <tr>
        <td><%= generation.user_id %></td>
        <td><%= generation.question_card_id %></td>
        <td><%= link_to 'Show', generation %></td>
        <td><%= link_to 'Edit', edit_generation_path(generation) %></td>
        <td><%= link_to 'Destroy', generation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Generation', new_generation_path %>

app/views/generations/my_generations.html.erb
<h1 class="page-header">
  <table width="100%"><tr>
    <td>История генераций:</td>
  </tr></table>
</h1>

<% if @generations.size == 0 %>
    <p>Вы еще не сенерировали ни одного билета.</p>
<% else %>
    <div class="list-group">
      <% @generations.each do |g| %>
          <%= render 'generations/list_item', generation: g %>
      <% end %>
    </div>

<% end %>

app/views/generations/new.html.erb
<h1>New Generation</h1>

<%= render 'form', generation: @generation %>

<%= link_to 'Back', generations_path %>

app/views/generations/question_card.html.erb
<% @cards.each do |card| %>
    <%= raw card %>
<% end %>

app/views/generations/question_card.pdf.erb
<meta charset="UTF-8">
<% @cards.each do |card| %>
  <%= raw card %>
<% end %>

app/views/generations/question_cards.html.erb
<% @cards.each do |card| %>
    <%= raw card %>
    <% case params[:page_layout].to_i %>
      <% when 0 %>
        <hr>
      <% when 1 %>
        <div style="page-break-after: always"></div>
    <% end %>
<% end %>

app/views/generations/question_cards.pdf.erb
<meta charset="UTF-8">
<% @cards.each do |card| %>
    <%= raw card %>
    <% case params[:page_layout].to_i %>
      <% when 0 %>
          <hr>
      <% when 1 %>
          <div style="page-break-after: always"></div>
    <% end %>
<% end %>

app/views/generations/show.html.erb
<h1 class="page-header">Сгенерированные билеты: <%= @generation.title %></h1>

<table width="100%">
  <tr>
    <td>
      <p>
        <strong>Пользователь:</strong>
        <i><a target="_blank" href="http://<%= @generation.user.email %>"><%= @generation.user.email %></a> </i>
      </p>
    </td>
    <td>
      <p style="text-align: right;">
        <%= @generation.created_at.to_formatted_s(:long) %>
      </p>
    </td>
  </tr>
</table>

<h3><b>Билет:</b> <%= @generation.question_card.title %></h3>
<p><b>Предмет:</b> <%= @generation.question_card.subject %></p>
<p><b>Описание:</b> <%= @generation.question_card.description %></p>
<p><b>Количество вариантов:</b> <%= @generation.variants.size %></p>

<div class="panel panel-primary">
  <div class="panel-heading">
    Генератор билетов
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
      <li class="active"><a href="#cards" data-toggle="tab" aria-expanded="false">Билеты</a>
      </li>
      <li class=""><a href="#answers" data-toggle="tab" aria-expanded="false">Ответы</a>
      </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div class="tab-pane fade in active" id="cards">
        <div class="row">
        <div class="col-md-4">
          <h4>Настройки генератора</h4>
        <%= form_tag("/generations/#{@generation.id}/question_cards.pdf", method: 'get', id: 'form-generator-cards') do %>
          <input type="checkbox" name="orientation" data-off-text="Альбомная" data-on-text="Книжная"
                 data-label-text="Ориентация" checked><br><br>
          <script>$("[name='orientation']").bootstrapSwitch();</script>
          <%= label_tag('Компановка на странице') %>
          <%= select_tag :page_layout, options_for_select(Rails.configuration.page_layouts), class: 'form-control' %>
              <br>
              <button type="submit" class="btn btn-success btn-block">
                <i class="fa fa-file-pdf-o"></i> Сгенерировать PDF'
              </button>
          <% end %>
        </div>
        </div><br>
        <div class="panel panel-info" id="view-question_cards">
          <div class="panel-heading"><span class="view-status"></span> Предпросмотр</div>
          <div class="panel-body view-result" ></div>
          <script>
            $().ready( get_html("view-question_cards", '<%= generation_path(@generation) + '/question_cards' %>') )
          </script>
        </div>
      </div>

      <div class="tab-pane fade" id="answers">
        <div class="row">
          <div class="col-md-4">
            <h4>Настройки генератора</h4>
            <%= form_tag("/generations/#{@generation.id}/answers.pdf", method: 'get', id: 'form-generator-answers') do %>
                <input type="checkbox" name="orientation" data-off-text="Альбомная"
                       data-on-text="Книжная" data-label-text="Ориентация" checked><br><br>
                <script>$("[name='orientation']").bootstrapSwitch();</script>
                <%= label_tag('Компановка на странице') %>
                <%= select_tag :page_layout, options_for_select(Rails.configuration.page_layouts), class: 'form-control' %>
                <br>
                <button type="submit" class="btn btn-success btn-block">
                  <i class="fa fa-file-pdf-o"></i> Сгенерировать PDF'
                </button>
            <% end %>
          </div>
        </div><br>
        <div class="panel panel-info" id="view-answers">
          <div class="panel-heading"><span class="view-status"></span> Предпросмотр</div>
          <div class="panel-body view-result" ></div>
          <script>$().ready( get_html("view-answers", '<%= generation_path(@generation) + '/answers' %>') )</script>
        </div>
      </div>
    </div>
  </div>
  <!-- /.panel-body -->
</div>


<%= link_to 'Back', generations_path %>