config/routes.rb
Rails.application.routes.draw do
  resources :images

  get '/generations/:id/question_cards', to: 'generations#question_cards'
  get '/generations/:id/answers', to: 'generations#answers'
  get 'generations/my', to: 'generations#my_generations'
  resources :generations

  get 'question_cards/my', to: 'question_cards#my_cards'
  get 'question_cards/:id/add_to_me', to: 'question_cards#add_to_me'
  resources :question_cards

  match 'tasks_groups/:id/add_task', to: 'tasks_groups#add_task', via: [:put]
  match 'tasks_groups/:id/remove_task', to: 'tasks_groups#remove_task', via: [:delete]
  get 'tasks_groups/my_groups'
  get 'tasks_groups/my', to: 'tasks_groups#my_groups'
  get 'tasks_groups/:id/add_to_me', to: 'tasks_groups#add_to_me'
  get 'tasks_groups/available_groups_for_add'
  resources :tasks_groups

  get 'tasks/my_tasks'
  get 'tasks/my', to: 'tasks#my_tasks'
  get 'tasks/:id/add_to_me', to: 'tasks#add_to_me'
  resources :tasks

  devise_for :users

  root 'main_page#index'

  get 'main_page/index'
  get 'main_page/welcome'
  get 'main_page/help'
  get 'help', to: 'main_page#help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  def index
    @tasks = current_user.tasks.where(removed: false).sort { |a, b| b.updated_at <=> a.updated_at }.take(5)
    @tasks_groups = current_user.tasks_groups.where(removed: false).sort { |a, b| b.updated_at <=> a.updated_at }.take(5)
    @generations = current_user.generations.sort { |a, b| b.updated_at <=> a.updated_at }.take(5)
    @question_cards = current_user.question_cards.where(removed: false).sort { |a, b| b.updated_at <=> a.updated_at }.take(5)
  end

  def welcome
  end

  def help
  end
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/views/main_page/_list.html.erb
<% if list.size == 0 %>
    <p><%= no_items %> Сделать это вы можете <a href="/<%= link %>/new">здесь</a></p>
<% else %>
    <div class="list-group">
      <% list.each do |item| %>
          <a href="/<%= link %>/<%= item.id %>" class="list-group-item list-group-item-action">
            <span class="pull-right text-muted small"><em><%= item.updated_at.to_formatted_s(:short)   %></em></span>
            <h4 class="list-group-item-heading"><%= item.title %></h4>
            <p class="list-group-item-text"><%= item.description %></p>
          </a>
      <% end %>
    </div>
    <a href="/<%= link %>/my" class="btn btn-default btn-block">Посмотреть все</a>
<% end %>

app/views/main_page/index.html.erb
<h1 class="page-header">Главная</h1>

<div class="row">
  <div class="col-lg-8">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <table width="100%"><tr>
          <td>Обзор билетов</td>
          <td width="70px" align="right">
            <%= link_to 'Добавить', new_question_card_path, class: 'btn btn-success btn-xs' %>
          </td>
        </tr></table>
      </div>
      <div class="panel-body">
        <% if @question_cards.size == 0 %>
            <p>Вы пока еще не создали ни одного билета. Сделать это вы можете
              <%= link_to 'здесь', new_question_card_path %>
            </p>
        <% else %>
            <%= render 'generations/generate_modal' %>
            <div class="list-group">
              <% @question_cards.each do |card| %>
                  <%= render 'question_cards/list_item', card: card %>
              <% end %>
            </div>
            <%= link_to 'Посмотреть все', question_cards_my_path, class: 'btn btn-default btn-block' %>
        <% end %>
      </div>
    </div>

    <div class="panel panel-red">
      <div class="panel-heading">
        <table width="100%"><tr>
          <td>Обзор задач</td>
          <td width="70px" align="right"><%= link_to 'Добавить', new_task_path, class: 'btn btn-success btn-xs' %></td>
        </tr></table>
      </div>
      <div class="panel-body">
        <% if @tasks.size == 0 %>
            <p>Вы пока еще не создали ни одной задачи. Сделать это вы можете <%= link_to 'здесь', new_task_path %></p>
        <% else %>
            <%= render 'tasks/add_task_to_group' %>
            <div class="list-group">
              <% @tasks.each do |task| %>
                  <%= render 'tasks/list_item', task: task %>
              <% end %>
            </div>
            <%= link_to 'Посмотреть все', tasks_my_path, class: 'btn btn-default btn-block' %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-lg-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-history fa-fw"></i> История генераций билетов
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <% if @generations.size == 0 %>
            <p>Вы пока еще не генерировали белеты</p>
        <% else %>
            <div class="list-group">
              <% @generations.each do |g| %>
                  <%= render 'generations/list_item', generation: g %>
              <% end %>
            </div>
            <a href="/generations/my" class="btn btn-default btn-block">Посмотреть все</a>
        <% end %>
      </div>
      <!-- /.panel-body -->
    </div>

    <div class="panel panel-info">
      <div class="panel-heading">
        <table width="100%"><tr>
          <td><i class="fa fa-list-alt fa-fw"></i> Обзор групп задач</td>
          <td width="70px" align="right">
            <%= link_to 'Добавить', new_tasks_group_path, class: 'btn btn-success btn-xs' %>
          </td>
        </tr></table>
      </div>
      <div class="panel-body">
        <% if @tasks_groups.size == 0 %>
            <p>Вы пока еще не создали ни одной группы задачи. Сделать это вы можете
              <%= link_to 'здесь', new_tasks_group_path %>
            </p>
        <% else %>
            <div class="list-group">
              <% @tasks_groups.each do |group| %>
                  <%= render 'tasks_groups/list_item', group: group %>
              <% end %>
            </div>
            <%= link_to 'Посмотреть все', tasks_groups_my_path, class: 'btn btn-default btn-block' %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/main_page/welcome.html.erb
<h1>MainPage#welcome</h1>
<p>Find me in app/views/main_page/welcome.html.erb</p>